repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: double-quote-string-fixer
  - repo: local
    hooks:
      - id: commitlint
        name: Commitlint
        language: system
        entry: npx commitlint --edit
        stages: [commit-msg]
