[build-system]
requires = ["setuptools>=64", "setuptools-scm>=8", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "qiskit_alice_bob_provider"
authors = [
    {name = "Alice & Bob Software Team"},
]
dynamic = ["version"]
description = "Provider for running Qiskit circuits on Alice & Bob QPUs and simulators"
readme = "README.md"
license = {text = "Apache 2.0"}
keywords = ["Qiskit", "Alice & Bob", "Quantum", "SDK"]
classifiers=[
    "Environment :: Console",
    "License :: OSI Approved :: Apache Software License",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: MacOS",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Scientific/Engineering :: Physics",
]
urls = {Homepage = "https://github.com/Alice-Bob-SW/qiskit-alice-bob-provider", "Alice & Bob" = "https://alice-bob.com/"}
requires-python = ">=3.9, <3.14"
dependencies = [
    "ipython",
    "ipywidgets",
    "pydantic>=2.0",
    "requests>=1.26",
    "qiskit>=1.3.1,<2.0",
    "qiskit-aer>=0.16.1,<0.18.0",
    "qiskit-qir-alice-bob-fork==0.5.0",
    "tenacity"
]

[dependency-groups]
dev = [
    "mock==5.1.0",
    "mypy==1.19.1",
    "mypy-extensions==1.0.0",
    "pre-commit>=2.21.0",
    "pytest==7.2.1",
    "requests==2.32.3",
    "requests-mock==1.10.0",
    "ruff==0.15.20",
    "traitlets==5.14.3",
    "types-mock==5.1.0",
    "types-requests==2.30.0.0"
]

[project.entry-points."qiskit.transpiler.scheduling"]
ab_asap = "qiskit_alice_bob_provider.plugins.ab_asap:AliceBobASAPSchedulingPlugin"

[project.entry-points."qiskit.transpiler.translation"]
state_preparation = "qiskit_alice_bob_provider.plugins.state_preparation:StatePreparationPlugin"
sk_synthesis = "qiskit_alice_bob_provider.plugins.sk_synthesis:SKSynthesisPlugin"

[tool.setuptools.packages.find]
include = ["qiskit_alice_bob_provider*"]

[tool.setuptools_scm]

[tool.ruff]
line-length = 79
target-version = "py39"

[tool.ruff.format]
quote-style = "single"
line-ending = "lf"

[tool.ruff.lint]
extend-select = [
    "I",  # isort
    "RUF100",  # useless noqa
]

[tool.mypy]
plugins = "numpy.typing.mypy_plugin"
disable_error_code = ['index']

[[tool.mypy.overrides]]
module = [
    "qiskit.*",
    "qiskit_qir.*",
    "qiskit_aer.*",
    "scipy.*"
]
ignore_missing_imports = true
